return {
	{ "chentoast/marks.nvim" },
	{ "nvim-tree/nvim-web-devicons" },
	{ "aznhe21/actions-preview.nvim" },
	{ "nvim-treesitter/nvim-treesitter" },
	{ "nvim-telescope/telescope.nvim" },
	{ "nvim-telescope/telescope-ui-select.nvim" },
	{ "nvim-lua/plenary.nvim" },
	{ "neovim/nvim-lspconfig" },
	{ "williamboman/mason.nvim" },
	{ "williamboman/mason-lspconfig.nvim" },
	{ "LinArcX/telescope-env.nvim" },
	{ "saecki/crates.nvim" },
	{ "MunifTanjim/nui.nvim" },
	{ "nvim-neo-tree/neo-tree.nvim" },
	{ "Mofiqul/vscode.nvim" },
	{ "mrcjkb/rustaceanvim" },
	{ "folke/trouble.nvim" },
	{ "tpope/vim-fugitive" },
	{ "nvim-lualine/lualine.nvim" },
	{ "j-hui/fidget.nvim" },
	{ "nvim-mini/mini.nvim", version = "*" },
}
